Repository mjugit/osdev, pull requests merged in 2022-09, with the labels that each got.

#20 Add parameters to bootloader.cfg tp prevent grub from showing menu
  src/iso/bootloader.cfg
Labels: enhancement

#21 #3 Fall back to EGA standard text mode for now
  src/boot.s
  src/include/vga.c
  src/include/vga.h
  src/kernel.c
Labels: enhancement

#25 Issue/#23 Improve repository structure
  README.md
  src/boot/boot.s
  src/boot/grub.cfg
  src/include/vga.c
  src/iso/bootloader.cfg
  src/kmain.c
  src/libc/.gitignore
  src/libc/include/string.h
  src/libc/string.c
  src/libk/.gitignore
  src/libk/font.c
  src/libk/include/font.h
  src/libk/include/vga.h
  src/libk/vga.c
  src/makefile
  ubuntu_build-toolchain.sh
Labels: enhancement

#26 Issue/#3 display driver
  src/kmain.c
  src/libk/include/vga.h
  src/libk/vga.c
Labels: enhancement

#27 Issue/#3 display driver
  src/kmain.c
  src/libc/.gitignore
  src/libk/.gitignore
  src/libk/include/vga.h
  src/libk/vga.c
Labels: enhancement

#30 Issue/#28 explain details
  README.md
  src/README.md
Labels: documentation

#31 Issue/#18 unit testing
  src/tests/example_preprocessed.c
  src/tests/test.c
  src/tests/utest.h
Labels: enhancement

#32 #18 Refactor unit testing header
  src/testing/example.c
  src/testing/include/utest.h
  src/tests/example_preprocessed.c
  src/tests/test.c
  src/tests/utest.h
Labels: enhancement

#37 Issue/#34 rewrite display driver
  src/kmain.c
  src/libk/include/kmem.h
  src/libk/include/vga.h
  src/libk/include/vga.h.bak
  src/libk/kmem.c
  src/libk/vga.c
  src/libk/vga.c.bak
  src/makefile
  src/testing/.gitignore
  src/testing/include/utest.h
  src/testing/libk/kmem_test.c
  src/testing/libk/vga_test.c
  src/testing/makefile
Labels: rewrite

#41 Issue/#40 prepare 0.1.0
  README.md
  src/kmain.c
  src/libk/include/vga.h
Labels: release

#42 Merge Version 0.1.0
  .gitignore
  README.md
  src/README.md
  src/boot.s
  src/boot/boot.s
  src/boot/grub.cfg
  src/iso/bootloader.cfg
  src/kernel.c
  src/kmain.c
  src/libc/include/string.h
  src/libc/string.c
  src/libk/font.c
  src/libk/include/font.h
  src/libk/include/kmem.h
  src/libk/include/vga.h
  src/libk/kmem.c
  src/libk/vga.c
  src/makefile
  src/testing/.gitignore
  src/testing/example.c
  src/testing/include/utest.h
  src/testing/libk/kmem_test.c
  src/testing/libk/vga_test.c
  src/testing/makefile
  toolchain/README.md
Labels: documentation, enhancement, release

#43 Issue/#29 implement printf
  src/kmain.c
  src/libk/include/kstd.h
  src/libk/include/vga.h
  src/libk/kstd.c
  src/libk/vga.c
  src/testing/.gitignore
  src/testing/libk/kstd_test.c
  src/testing/libk/vga_test.c
  src/testing/makefile
Labels: enhancement, rewrite

#51 A little fix for kprintf
  src/boot/boot.s
  src/kmain.c
  src/libk/include/kstd.h
  src/libk/include/vga.h
  src/libk/kbase.s
  src/libk/kstd.c
  src/libk/vga.c
  src/makefile
Labels: bug
